export enum ObjectName {
    DOOR_START = 'door_start',
    DOOR_END = 'door_end',
    START = 'start',
    END = 'end',
    DIALOG = 'dialog',
    DOOR_TP_GREEN_1 = 'door_tp_green_1',
    DOOR_TP_GREEN_2 = 'door_tp_green_2',
    DOOR_TP_RED_1 = 'door_tp_red_1',
    DOOR_TP_RED_2 = 'door_tp_red_2',
    TP_SIMPLE = 'tp_simple',
    TP_DOUBLE_1 = 'tp_double_1',
    TP_DOUBLE_2 = 'tp_double_2',
    TP_MULTI_1 = 'tp_multi_1',
    TP_MULTI_2 = 'tp_multi_2',
    TP_MULTI_3 = 'tp_multi_3',
    SWITCHER_SIMPLE = 'switcher_simple',
    SWITCHER_DOUBLE = 'switcher_double',
    SWITCHER_MULTI_1 = 'switcher_multi_1',
    SWITCHER_MULTI_2 = 'switcher_multi_2',
    SWITCHER_MULTI_3 = 'switcher_multi_3',
}
