export enum SceneKey {
  BaseLevel = 'BaseLevel',
  PreloadStartScreen = 'PreloadStartScreen',
  StartScreen = 'StartScreen',
  PreloadLevel1 = 'PreloadLevel1',
  Level1 = 'Level1',
  PreloadLevel2 = 'PreloadLevel2',
  Level2 = 'Level2',
  PreloadLevel3 = 'PreloadLevel3',
  Level3 = 'Level3',
  PreloadLevel4 = 'PreloadLevel4',
  Level4 = 'Level4',
  PreloadLevel5 = 'PreloadLevel5',
  Level5 = 'Level5',
  PreloadLevel6 = 'PreloadLevel6',
  Level6 = 'Level6',
  PreloadLevel7 = 'PreloadLevel7',
  Level7 = 'Level7',
  PreloadLevel8 = 'PreloadLevel8',
  Level8 = 'Level8',
}